# Generated by the private renderer release process.
RENDERER_MANIFEST_SHA256: str | None = None
RENDERER_RELEASES: dict[str, str] = {'windows-x86_64': 'd93f1e73b71320e9345dc1f40b6f1dfd0e7e7db34509b6448c7847e766643cca', 'linux-x86_64': '1bff7b671184570cccef3b4991417bceeda543c5456e9ca287efd345e20d42f4'}
