# Generated by the private renderer release process.
RENDERER_MANIFEST_SHA256: str | None = None
RENDERER_RELEASES: dict[str, str] = {'windows-x86_64': 'c5008ce04325ad47f5273ed6d1e439c555f97a691ddf6cc7fa4eac9629db516e', 'linux-x86_64': 'd4d35cf1a937dcaf320382bfee2a56373408568b05ddececc2031d8ad240b9fa'}
